{% set name = "popt" %}
{% set version = "1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://ftp.rpm.org/{{ name|lower }}/releases/{{ name|lower }}-1.x/{{ name|lower }}-{{ version }}.tar.gz
    sha256: c25a4838fc8e4c1c8aacb8bd620edb3084a3d63bf8987fdad3ca2758c63240f9

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}


requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - libiconv
    - perl
    - make
  run:
    - libiconv

test:
  commands:
    - test -f $PREFIX/include/popt.h
    - test -f $PREFIX/lib/libpopt.a
    - test -f $PREFIX/lib/libpopt.so  # [linux]
    - test -f $PREFIX/lib/libpopt.dylib  # [osx]

about:
  home: http://rpm5.org/
  license: MIT
  license_file: COPYING
  summary: 'Popt is a C library for parsing command line parameters.'

extra:
  recipe-maintainers:
    - notestaff
    - sodre
